-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

/*USE ecommerce_db;

CREATE TABLE Category (
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE Product (
id INT PRIMARY KEY NOT NULL,
name VARCHAR(30) NOT NULL,
price DECIMAL NOT NULL,
stock INT NOT NULL,
);

CREATE TABLE Tag (
id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
name VARCHAR(30),


);

CREATE TABLE ProductTag (
id INT PRIMARY KEY NOT NULL,
product id INT PRIMARY KEY NOT NULL,
tag id INT PRIMARY KEY NOT NULL,
);
